export interface Game {
  slug: string;
  title: string;
  titleZh: string;
  emoji: string;
  description: string;
  descriptionZh: string;
  url: string;
  category: string;
  rating: number;
  plays: string;
  tag?: 'HOT' | 'NEW' | '';
  gradient: string;
  borderColor: string;
  subtitle: string;
  instructions: { keys: string; action: string }[];
}

export const games: Game[] = [
  {
    slug: 'sea-kings',
    title: 'Sea Kings',
    titleZh: '海贼王海战',
    emoji: '🏴‍☠️',
    description: 'Rule the waves! Command your pirate ship, blast enemies with cannons, and become the King of the Sea.',
    descriptionZh: '统治海洋！指挥你的海盗船，用大炮轰沉敌人，成为海贼王！',
    url: 'https://html5.gamemonetize.co/azd2160bf0hum6z3y5miuyxym0yjnqxw/',
    category: 'Action',
    rating: 4.8,
    plays: '45.2K',
    tag: 'HOT',
    gradient: 'from-red-500/20 to-orange-500/20',
    borderColor: 'border-red-500/30',
    subtitle: 'Clash of Pirates',
    instructions: [
      { keys: 'Mouse', action: 'Aim & fire' },
      { keys: '⚔️', action: 'Sink enemies' },
      { keys: '⬆️', action: 'Upgrade ship' },
    ],
  },
  {
    slug: 'fruit-merger',
    title: 'Fruit Merger',
    titleZh: '果实合并',
    emoji: '🍒',
    description: 'Merge matching fruits to create bigger, juicier evolutions. A Devil Fruit puzzle!',
    descriptionZh: '合并相同水果，进化出更大更 juicy 的果实。恶魔果实益智游戏！',
    url: 'https://html5.gamemonetize.co/y1z2j6chycgz55jmcxkxhznshlf17dl6/',
    category: 'Puzzle',
    rating: 4.5,
    plays: '28.7K',
    tag: 'NEW',
    gradient: 'from-purple-500/20 to-pink-500/20',
    borderColor: 'border-purple-500/30',
    subtitle: 'Devil Fruit Merger',
    instructions: [
      { keys: 'Click', action: 'Drop fruit' },
      { keys: '🎯', action: 'Merge & evolve' },
    ],
  },
  {
    slug: 'fruit-island',
    title: 'Fruit Island',
    titleZh: '果实岛冒险',
    emoji: '🏝️',
    description: 'Adventure on Fruit Island! Collect fruits and explore with friends.',
    descriptionZh: '在果实岛上冒险！收集水果，和好友一起探索。',
    url: 'https://html5.gamemonetize.co/7xq1ndi04moqr45f9g9zwjqosib0rkhy/',
    category: 'Adventure',
    rating: 4.3,
    plays: '19.4K',
    tag: '',
    gradient: 'from-blue-500/20 to-cyan-500/20',
    borderColor: 'border-blue-500/30',
    subtitle: 'Fruit Island Adventure',
    instructions: [
      { keys: 'WAD', action: 'P1 move' },
      { keys: '←→↑', action: 'P2 move' },
    ],
  },
  {
    slug: 'devil-fruit-hunter',
    title: 'Devil Fruit Hunter',
    titleZh: '恶魔果实猎人',
    emoji: '🍎',
    description: 'Collect Devil Fruits across the Grand Line. Avoid the Sea Kings!',
    descriptionZh: '收集果实，躲避炸弹，成为海贼王！',
    url: '/games/devil-fruit-hunter.html',
    category: 'Action',
    rating: 4.6,
    plays: '12.5K',
    tag: '',
    gradient: 'from-red-500/20 to-orange-500/20',
    borderColor: 'border-red-500/30',
    subtitle: 'Devil Fruit Hunter',
    instructions: [
      { keys: '← →', action: 'Move' },
      { keys: '🍎', action: '+100 pts' },
      { keys: '🌟', action: '+500 pts' },
      { keys: '💣', action: '-50 pts' },
      { keys: '❤️', action: '3 lives' },
    ],
  },
  {
    slug: 'ocean-maze',
    title: 'Ocean Maze',
    titleZh: '航海迷宫',
    emoji: '🌊',
    description: 'Navigate through the treacherous Grand Line waters.',
    descriptionZh: '在伟大航路的危险水域中航行。',
    url: '/games/ocean-maze.html',
    category: 'Puzzle',
    rating: 4.2,
    plays: '5.2K',
    tag: '',
    gradient: 'from-blue-500/20 to-cyan-500/20',
    borderColor: 'border-blue-500/30',
    subtitle: 'Ocean Maze Explorer',
    instructions: [
      { keys: 'WASD', action: 'Navigate' },
      { keys: '🎯', action: 'Reach the goal' },
    ],
  },
  {
    slug: 'fruit-battle',
    title: 'Fruit Battle',
    titleZh: '果实对战',
    emoji: '⚔️',
    description: 'Battle with Devil Fruit powers in this arena fighter.',
    descriptionZh: '在竞技场中用恶魔果实能力对战。',
    url: '/games/fruit-battle.html',
    category: 'Battle',
    rating: 4.0,
    plays: '3.8K',
    tag: '',
    gradient: 'from-purple-500/20 to-pink-500/20',
    borderColor: 'border-purple-500/30',
    subtitle: 'Devil Fruit Battle Arena',
    instructions: [
      { keys: 'Q/W/E', action: 'Skills' },
      { keys: 'Space', action: 'Attack' },
    ],
  },
  {
    slug: 'treasure-hunt',
    title: 'Treasure Hunt',
    titleZh: '寻宝探险',
    emoji: '💎',
    description: 'Search for hidden treasures across exotic islands.',
    descriptionZh: '在异域岛屿上搜寻隐藏的宝藏。',
    url: '/games/treasure-hunt.html',
    category: 'Adventure',
    rating: 4.3,
    plays: '6.7K',
    tag: '',
    gradient: 'from-green-500/20 to-emerald-500/20',
    borderColor: 'border-green-500/30',
    subtitle: 'Treasure Hunt Adventure',
    instructions: [
      { keys: 'Click', action: 'Dig treasure' },
      { keys: '⏱️', action: 'Beat the clock' },
    ],
  },
  {
    slug: 'parkour-challenge',
    title: 'Parkour Challenge',
    titleZh: '跑酷挑战',
    emoji: '🏃',
    description: 'Jump, dash and climb through pirate obstacles.',
    descriptionZh: '在海盗障碍中跳跃、冲刺和攀爬。',
    url: '/games/parkour-challenge.html',
    category: 'Action',
    rating: 4.1,
    plays: '4.5K',
    tag: '',
    gradient: 'from-yellow-500/20 to-amber-500/20',
    borderColor: 'border-yellow-500/30',
    subtitle: 'Pirate Parkour Challenge',
    instructions: [
      { keys: 'Space', action: 'Jump' },
      { keys: 'Shift', action: 'Dash' },
    ],
  },
  {
    slug: 'memory-cards',
    title: 'Memory Cards',
    titleZh: '记忆翻牌',
    emoji: '🃏',
    description: 'Match Devil Fruit pairs in this memory game.',
    descriptionZh: '在记忆游戏中配对恶魔果实。',
    url: '/games/memory-cards.html',
    category: 'Puzzle',
    rating: 3.9,
    plays: '2.1K',
    tag: '',
    gradient: 'from-indigo-500/20 to-violet-500/20',
    borderColor: 'border-indigo-500/30',
    subtitle: 'Memory Card Match',
    instructions: [
      { keys: 'Click', action: 'Flip card' },
      { keys: '🎯', action: 'Match pairs' },
    ],
  },
  {
    slug: 'shooting-range',
    title: 'Shooting Range',
    titleZh: '射击训练',
    emoji: '🎯',
    description: 'Train your aim at the Marine shooting range.',
    descriptionZh: '在海军射击场训练你的瞄准能力。',
    url: '/games/shooting-range.html',
    category: 'Shooting',
    rating: 4.4,
    plays: '8.3K',
    tag: '',
    gradient: 'from-rose-500/20 to-red-500/20',
    borderColor: 'border-rose-500/30',
    subtitle: 'Marine Shooting Range',
    instructions: [
      { keys: 'Mouse', action: 'Aim & shoot' },
      { keys: 'R', action: 'Reload' },
    ],
  },
  {
    slug: 'puzzle-master',
    title: 'Puzzle Master',
    titleZh: '拼图大师',
    emoji: '🧩',
    description: 'Solve pirate-themed jigsaw puzzles.',
    descriptionZh: '解决海盗主题拼图。',
    url: '/games/puzzle-master.html',
    category: 'Puzzle',
    rating: 3.7,
    plays: '1.8K',
    tag: '',
    gradient: 'from-teal-500/20 to-cyan-500/20',
    borderColor: 'border-teal-500/30',
    subtitle: 'Puzzle Master Challenge',
    instructions: [
      { keys: 'Drag', action: 'Move pieces' },
      { keys: '🎯', action: 'Complete image' },
    ],
  },
];

export const categories = [
  { id: 'action', name: 'Action', nameZh: '动作', emoji: '🎮', count: 28, gradient: 'from-red-500/20 to-orange-500/20', borderColor: 'border-red-500/30' },
  { id: 'puzzle', name: 'Puzzle', nameZh: '益智', emoji: '🧠', count: 21, gradient: 'from-blue-500/20 to-cyan-500/20', borderColor: 'border-blue-500/30' },
  { id: 'parkour', name: 'Parkour', nameZh: '跑酷', emoji: '🏃', count: 12, gradient: 'from-purple-500/20 to-pink-500/20', borderColor: 'border-purple-500/30' },
  { id: 'shooting', name: 'Shooting', nameZh: '射击', emoji: '🎯', count: 15, gradient: 'from-green-500/20 to-emerald-500/20', borderColor: 'border-green-500/30' },
  { id: 'racing', name: 'Racing', nameZh: '竞速', emoji: '🏎️', count: 9, gradient: 'from-yellow-500/20 to-amber-500/20', borderColor: 'border-yellow-500/30' },
  { id: 'multiplayer', name: 'Multiplayer', nameZh: '多人', emoji: '👥', count: 8, gradient: 'from-indigo-500/20 to-violet-500/20', borderColor: 'border-indigo-500/30' },
  { id: 'battle', name: 'Battle', nameZh: '对战', emoji: '⚔️', count: 11, gradient: 'from-rose-500/20 to-red-500/20', borderColor: 'border-rose-500/30' },
  { id: 'card', name: 'Card', nameZh: '卡牌', emoji: '🃏', count: 6, gradient: 'from-teal-500/20 to-cyan-500/20', borderColor: 'border-teal-500/30' },
];

export function getGameBySlug(slug: string): Game | undefined {
  return games.find((g) => g.slug === slug);
}
